---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name postgres
spec:
  postgresVersion: 16

  metadata:
    labels:
      crunchy-userinit.ramblurr.github.com/enabled: "true"
      crunchy-userinit.ramblurr.github.com/superuser: "postgres"

  service:
    type: LoadBalancer
    metadata:
      annotations:
        lbipam.cilium.io/ips: 10.0.2.201

  # patroni: # turn on sync writes to at least 1 other replica
  #   dynamicConfiguration:
  #     synchronous_mode: true
  #     postgresql:
  #       max_wal_size: 5GB
  #       synchronous_commit: "on"
  #       pg_hba:
  #         - hostnossl all all 10.244.0.0/16 md5 # Needed because dbman does not support SSL yet
  #         - hostssl all all all md5

  patroni:
    dynamicConfiguration:
      postgresql:
        pg_hba:
          - "hostnossl all all all md5"
          - "host all all all md5"

  instances:
    - name: postgres
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  users:
    # Superuser
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password:
        type: AlphaNumeric
    # Applications
    - name: infisical
      databases:
        - infisical
      password:
        type: AlphaNumeric
    - name: linkwarden
      databases:
        - linkwarden
      password:
        type: AlphaNumeric
    - name: entertainment
      databases:
        - jellystat
      password:
        type: AlphaNumeric
    - name: nextcloud
      databases:
        - nextcloud
      password:
        type: AlphaNumeric
    - name: romm
      databases:
        - romm
      password:
        type: AlphaNumeric
    - name: trina
      databases:
        - WordsBot
      password:
        type: AlphaNumeric
    - name: authentik
      databases:
        - authentik
      password:
        type: AlphaNumeric
    - name: mediamanager
      databases:
        - mediamanager
      password:
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &backupConfig []
      global: &backupFlag
        compress-type: "bz2"
        compress-level: "9"
        # NFS
        repo1-bundle: "y"
        repo1-retention-full: "30" # days
        repo1-retention-full-type: "time"
      manual:
        repoName: repo1
        options:
          - --type=full
      metadata:
        labels:
          app.kubernetes.io/name: crunchy-postgres-backup
      repos:
        - name: repo1 # NFS
          volume: &nfs
            volumeClaimSpec:
              storageClassName: postgres-nfs
              volumeName: postgres-nfs
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: "1Mi"
          schedules:
            full: "0 1 * * 0" # Sunday at 01:00
            differential: "0 1 * * 1-6" # Mon-Sat at 01:00
            incremental: "0 2-23 * * *" # Every hour except 01:00
  dataSource:
    postgresCluster:
      clusterName: postgres
      repoName: repo1

  # monitoring:
  #   pgmonitor:
  #     exporter:
  #       resources:
  #         requests:
  #           cpu: 10m
  #           memory: 64M
  #         limits:
  #           memory: 512M

  # proxy:
  #   pgBouncer:
  #     port: 5432
  #     replicas: *replica
  #     metadata:
  #       labels:
  #         app.kubernetes.io/name: crunchy-postgres-pgbouncer
  #     config:
  #       global:
  #         pool_mode: "transaction" # pgBouncer is set to transaction for Authentik. Grafana requires session https://github.com/grafana/grafana/issues/74260#issuecomment-1702795311. Everything else is happy with transaction
  #         client_tls_sslmode: prefer
  #     topologySpreadConstraints:
  #       - maxSkew: 1
  #         topologyKey: "kubernetes.io/hostname"
  #         whenUnsatisfiable: "DoNotSchedule"
  #         labelSelector:
  #           matchLabels:
  #             postgres-operator.crunchydata.com/cluster: *name
  #             postgres-operator.crunchydata.com/role: "pgbouncer"
