apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &name qbittorrent
  namespace: flux-system
spec:
  targetNamespace: entertainment
  interval: 10m0s
  retryInterval: 1m
  path: ./kubernetes/apps/entertainment/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
  postBuild:
    substitute:
      app: *name
      webui-port: "8080"
      torrent-port: "6881"
      host: "qbittorrent.${SECRET_PRIVATE_DOMAIN}"
